stages:
  - checkstyle
  - test
  - build

variables:                         &default-vars
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       100
  CARGO_INCREMENTAL:               0

.test:                             &test
  script:
    - cargo test --workspace

.build:                             &build
  script:
    - cargo build --locked --all
    - cargo doc -p subwasm -p subwasmlib -p wasm-loader -p wasm-testbed -p substrate-runtime-proposal-hash --all-features --no-deps

.only:                             &only
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/

.only_tags:                             &only_tags
  only:
    - triggers
    - tags

.docker-env:                       &docker-env
  image:                           rust:latest
  before_script:
    - rustup show
    - cargo --version
    # - sccache -s
  variables:
    <<:                            *default-vars
    CARGO_TARGET_DIR:              "/ci-cache/${CI_PROJECT_NAME}/targets/${CI_COMMIT_REF_NAME}/${CI_JOB_NAME}"
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  interruptible:                   true
  tags:
    - docker

checkstyle-linux-stable:
  stage:                           checkstyle
  <<:                              *only
  <<:                              *docker-env
  script:
    - rustup component add rustfmt clippy
    - cargo fmt --all -- --check
    - cargo clippy
  allow_failure:                   false

test-linux-stable:
  stage:                           test
  <<:                              *docker-env
  <<:                              *only
  <<:                              *test

build:
  stage:                           build
  <<:                              *docker-env
  <<:                              *only_tags
  <<:                              *build
