# This workflow runs on every push and checks whether everything looks good

name: Quick check

on:
  push:
    tags:
      - "v*"

jobs:
  linux:
    env:
      TARGET_DIR: target/release

    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo "TAG=$TAG" >> $GITHUB_ENV
      - uses: actions/checkout@v2

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb

      - name: Build deb
        shell: bash
        run: |
          cargo deb
