# This workflow runs on every push and checks whether everything looks good

name: Build Linux Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  linux:
    env:
      TARGET_DIR: target/release

    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo "TAG=$TAG" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install cargo deb
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb

      - name: Build deb
        shell: bash
        run: |
          cargo deb -p subwasm -o "subwasm_linux_amd64_${{ env.RELEASE_VERSION }}.deb"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: subwasm_linux_amd64_${{ env.RELEASE_VERSION }}
          path: |
            subwasm_linux_amd64_${{ env.RELEASE_VERSION }}.deb

  create_draft:
    needs: ["linux"]
    name: Create Draft
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create-release.outputs.html_url }}
      asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v2

      - name: Generate changelog
        id: change_log
        run: |
          OUT=`git log $(git describe --tags --abbrev=0)..HEAD --oneline`
          echo "::set-output name=changes::$OUT"

      - name: Create Draft Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Tera ${{ env.RELEASE_VERSION }}
          body: |
            # Description
            You can find the changelogs below.

            # Downloads
            Download the binary for your OS from below:
            - **Linux**
              - [deb package](https://github.com/chevdor/subwasm/releases/download/${{ env.RELEASE_VERSION }}/subwasm_linux_amd64_${{ env.RELEASE_VERSION }}.deb)

            # Release Highlights
            ----
            These were the highlights. Check below for the full changelog :point_down:
            ${{ steps.change_log.outputs.changes }}
          draft: true

  publish-binaries:
    runs-on: ubuntu-latest
    needs: ["create_draft"]
    steps:
      - uses: actions/checkout@v2
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/download-artifact@v2
      - name: debug
        shell: bash
        run: |
          echo ${{ github.workspace }}
      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.asset_upload_url }}
          asset_path: "subwasm_linux_amd64_${{ env.RELEASE_VERSION }}/subwasm_linux_amd64_${{ env.RELEASE_VERSION }}.deb"
          asset_name: "subwasm_linux_amd64_${{ env.RELEASE_VERSION }}.deb"
          asset_content_type: application/vnd.debian.binary-package
