# This workflow runs on every push and checks whether everything looks good

name: Build Linux Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  linux:
    env:
      TARGET_DIR: target/release

    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo "TAG=$TAG" >> $GITHUB_ENV
      - uses: actions/checkout@v2

      - name: Install cargo deb
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb

      - name: Build deb
        shell: bash
        run: |
          cargo deb -p subwasm

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: subwasm-linux-deb-${{ github.sha }}
          path: |
            target/debian/*.deb
  